# Generated by Django 3.2.7 on 2021-10-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eproduct',
            old_name='S_wat',
            new_name='s_wat',
        ),
    ]
